3lessonproject/Controllers/SchoolController.cs
using _3lessonproject.Helpers;
using _3lessonproject.Models;
using Classroom.Data.Context;
using Classroom.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace _3lessonproject.Controllers;

public class SchoolController : Controller
{
    private readonly AppDbContext _context;
    private readonly UserProvider _userProvider;


    public SchoolController(AppDbContext context,UserProvider userProvider)
    {
        _context = context;
        _userProvider = userProvider;
    }


    [HttpGet]
    public IActionResult CreateSchool()
    {
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> CreateSchool([FromForm] CreateSchoolDto createSchoolDto)
    {
        if (!ModelState.IsValid)
        {
            return View(createSchoolDto);
        }

        var school = new School()
        {
            Name = createSchoolDto.Name,
            Description = createSchoolDto.Description
        };

        if (createSchoolDto.Photo != null)
        {
            school.PhotoUrl = await FileHelper.SaveSchoolFile(createSchoolDto.Photo);
        }

       // var userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

        school.UserSchools = new List<UserSchool>()
{
   new UserSchool()
   {
       UserId = _userProvider.UserId,
       Type = EUserSchool.Creater
   }
};

        _context.School.Add(school);
        await _context.SaveChangesAsync();

        return RedirectToAction("Index");
    }


    public async Task<IActionResult> Index()
    {
        var schools = await _context.School
            .Include(school => school.UserSchools)
            .ToListAsync();

        return View(schools);
    }

    public async Task<IActionResult> GetSchoolById(Guid id)
    {
        var school = await _context.School
            .Include(school => school.UserSchools)
                .ThenInclude(userSchool => userSchool.User)
            .FirstOrDefaultAsync(x => x.Id == id);

        return View(school);
    }


    public async Task<IActionResult> JoinSchool(Guid id)
    {
        var school = await _context.School
            .Include(s => s.UserSchools)
            .ThenInclude(u => u.User)
            .FirstOrDefaultAsync(s => s.Id == id);

        var userId = _userProvider.UserId;
        var isUserExistsInSchool = school.UserSchools.Any(u => u.User.Id == userId);

        if (!isUserExistsInSchool)
        {
            school.UserSchools.Add(new UserSchool()
            {
                UserId = userId,
                Type = EUserSchool.Student
            });
        }

        await _context.SaveChangesAsync();
        return RedirectToAction("GetSchoolById", new { id = school.Id });
    }

    [HttpGet]
    public async Task<IActionResult> UpdateSchool(Guid id)
    {
        var school = await _context.School
            .FirstOrDefaultAsync(s => s.Id == id);

        ViewBag.Id = id;

        return View(new UpdateSchoolDto()
        {
            Name = school.Name,
            Description = school.Description
        });
    }

    [HttpPost]
    public async Task<IActionResult> UpdateSchool(Guid id,[FromForm]UpdateSchoolDto updateSchoolDto)
    {
        var school = await _context.School
            .FirstOrDefaultAsync(s => s.Id == id);

        school.Name = updateSchoolDto.Name;
        school.Description = updateSchoolDto.Description;

        if(updateSchoolDto.Photo != null)
        school.PhotoUrl = await FileHelper.SaveSchoolFile(updateSchoolDto.Photo);

        await _context.SaveChangesAsync();

        return RedirectToAction("GetSchoolById",new {id = school.Id });

    }


    public async Task<IActionResult> UpdateUserSchoolRole(Guid schoolId, Guid userId, EUserSchool role)
    {
        var userSchool = await _context.UserSchool
            .FirstOrDefaultAsync(u => u.UserId == userId && u.SchoolId == schoolId);

        if (userSchool.Type != EUserSchool.Creater && role != EUserSchool.Creater)
            userSchool.Type = role;

        await _context.SaveChangesAsync();

        return RedirectToAction("GetSchoolById", new { id = schoolId });
    }

}

3lessonproject/Controllers/UsersController.cs
using _3lessonproject.Helpers;
using _3lessonproject.Models;
using Classroom.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace _3lessonproject.Controllers;

public class UsersController : Controller
{
    private readonly UserManager<User> _userManager;
    private readonly SignInManager<User> _signInManager;

    public UsersController(UserManager<User> userManager, SignInManager<User> signInManager)
    {
        _userManager = userManager;
        _signInManager = signInManager;
    }

    [HttpGet]
    public IActionResult SignUp()
    {



        return View();
    }

    [HttpPost]
    public async Task<IActionResult> SignUp([FromForm]CreateUserDto createUserDto)
    {
        if(!ModelState.IsValid)
        {
            return View(createUserDto);
        }

        var user = new User()
        {
            FirstName = createUserDto.FirstName,
            LastName = createUserDto.LastName,
            PhoneNumber = createUserDto.PhoneNumber,
            UserName = createUserDto.UserName,
        };

        user.PhotoUrl = await FileHelper.SaveUserFile(createUserDto.Photo);

        var result = await _userManager.CreateAsync(user,createUserDto.Password);

        if(!result.Succeeded)
        {
            ModelState.AddModelError("UserName", result.Errors.First().Description);

            return View();
        }

        await _signInManager.SignInAsync(user,isPersistent: true);


        return RedirectToAction("Index","Home");
    }


    [Authorize]
    public async Task<IActionResult> Profile()
    {
        var user = await _userManager.GetUserAsync(User);
        return View(user);
    }




    [HttpGet]
    public IActionResult  SignIn()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> SignIn([FromForm]SigninUserDto signinUserDto )
    {

        var result = await _signInManager.PasswordSignInAsync(signinUserDto.UserName, signinUserDto.Password,true,false);

        if(!result.Succeeded)
        {
            ModelState.AddModelError("UserName", "UserName or Password is incorrecrt");
            return View();
        }

        return RedirectToAction("Profile");
    }



    [Authorize]
    public async Task<IActionResult> LogOut()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction("SignIn");
    }
}

3lessonproject/Views/Shared/JoinSchoolLink.cshtml
@using _3lessonproject.Helpers
@model Classroom.Data.Entities.School
@inject UserProvider UserProvider

@{
    var userId = UserProvider.UserId;
    var isUserExistsInSchool = Model.UserSchools!.Any(user => user.User.Id == userId);
    if (!isUserExistsInSchool)
    {
        <a class="btn btn-primary" asp-action="JoinSchool" asp-route-id="@Model.Id">Join</a>
    }
}

3lessonproject/Views/Shared/UpdateSchoolLink.cshtml
@using _3lessonproject.Helpers
@using Classroom.Data.Entities
@model Classroom.Data.Entities.School
@inject UserProvider UserProvider


@{
    if (Model.UserSchools.Any(s=>s.UserId == UserProvider.UserId
        &&(s.Type ==EUserSchool.Creater||s.Type==EUserSchool.Admin)))
    {
        <a class="btn btn-primary"
        asp-controller="School"
        asp-action="UpdateSchool"
        asp-route-id="@Model.Id">Update</a>
    }
}

3lessonproject/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClassRoomMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClassRoomMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClassRoomMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="School" asp-action="Index">School</a>
                        </li>
                    </ul>
                    @if (!User.HasClaim(claim => claim.Type == ClaimTypes.NameIdentifier))
                    {
                        <ul class="navbar-text" style="list-style: none; display: flex;gap: 5px;">
                            <li class="nav-item">
                                <a class="btn btn-primary" asp-area="" asp-controller="Users" asp-action="SignIn" asp-route-id="1">Sign In</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-primary" asp-area="" asp-controller="Users" asp-action="SignUp" asp-route-id="1">Sign Up</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-text" style="list-style: none; display: flex;gap: 5px;">
                            <li class="nav-item">
                                <a class="btn btn-primary" asp-area="" asp-controller="Users" asp-action="Profile" asp-route-id="1">Profile</a>
                            </li>

                        </ul>
                    }


                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ClassRoomMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>